### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ro",
  "email": "ro@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "ro@gmail.com",
  "password": "password"
}

###
### Photos create
POST http://localhost:3000/dogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMxNDgxMTd9.tUbU6HBQOFf8pMoo5cqNIYxlCJI8s2NBe_Pe1dbcn2s

{
  "name": "Yupy",
  "age": 1,
  "breed": "Pomeranian"
}